Modified README files
cs-pub-ro/computer-architecture pull request #18
Opened 2024-10-14 23:00 UTC by aidanozo

# Prerequisite Checklist

- [x] Read the [contribution guidelines](https://github.com/open-education-hub/oer-template/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [x] Tested your changes against relevant architectures and platforms;
- [x] Updated relevant documentation (if needed).

## Description of changes
Modified README files for Lab2 exercises.

2024-10-15 17:44 UTC, sdcioc commented on chapters/verilog/operators/drills/README.md
We want to try to explain the solution now. It is no longer an exercise for the students. It is more about following the solution and understanding it.

2024-10-15 17:53 UTC, sdcioc requested changes
We want to try to explain the solution now. It is no longer an exercise for the students. It is more about following the solution and understanding it.

2024-10-30 07:37 UTC, DTeodor-Alexaandru commented
Is this PR still relevant?

2024-11-04 05:19 UTC, sdcioc commented
> Is this PR still relevant?

for the next year maybe.

2024-11-04 05:44 UTC, DTeodor-Alexaandru commented
@aidanozo Please rebase and we will merge this asap to close this PR

2024-11-05 17:33 UTC, closed without merging