Fix/lab5
cs-pub-ro/computer-architecture pull request #22
Opened 2024-10-17 19:58 UTC by Golem211

# Prerequisite Checklist

- [ x] Read the [contribution guidelines](https://github.com/open-education-hub/oer-template/blob/main/CONTRIBUTING.md#pull-requests) regarding submitting new changes to the project;
- [ ] Tested your changes against relevant architectures and platforms;
- [ x] Updated relevant documentation (if needed).

## Description of changes

2024-10-18 05:07 UTC, sdcioc commented on chapters/verilog/memory/drills/tasks/register/register.v
>      parameter p_data_width = 7
we can make it on 8 bits

2024-10-18 05:08 UTC, sdcioc commented on chapters/verilog/memory/drills/tasks/register/register.xdc
We can use the the first 8 leds for out and that last 8 leds for disp_out. We can use the first 8 switches for the in, and the next three for reset, we, oe. we can connect the CLK from the FPGA CLK.

2024-10-18 05:13 UTC, sdcioc commented on chapters/verilog/memory/drills/tasks/sequential_multiplier/sequential_multiplier.xdc
we can use first 4 switches for a, next 4 for b, after reset, clk, write, multiply. This time I think it is better to have manual control over the clock. It will be easier to understand. And the first 8 leds will be for output. We can add disp_a and disp_b to se on leds also the values of a and b in the registers.

2024-10-18 05:15 UTC, sdcioc commented on chapters/verilog/memory/drills/README.md
We don't have anymore a lab skeleton, so we need to change this README more to explain the solution and why we chose to do this steps in implementation.

2024-10-24 07:55 UTC, Golem211 commented on chapters/verilog/memory/drills/tasks/sequential_multiplier/sequential_multiplier.xdc
what do you mean by this : "We can add disp_a and disp_b to se on leds also the values of a and b in the registers."
please elaborate.
Also, sequential_multiplier i think is not finished because i cannot find where is the implementation of every state:
case(state)
        STATE_WRITE:
               logic for this state...

2024-10-30 07:38 UTC, DTeodor-Alexaandru commented on chapters/verilog/memory/drills/tasks/sequential_multiplier/sequential_multiplier.xdc
@sdcioc

2024-10-30 16:24 UTC, DTeodor-Alexaandru requested changes
Please explain the solution in order for students to understand it

2024-10-30 22:13 UTC, Golem211 commented on chapters/verilog/memory/drills/tasks/sequential_multiplier/sequential_multiplier.xdc
After a few hours of reviewing the code, I understand that the old logic using case statements has been updated as follows:
`assign l_w_a_we = l_r_state == STATE_WRITE; 
    assign l_w_a_oe = l_r_state == STATE_MULTIPLY;
    assign l_w_b_we = l_r_state == STATE_WRITE; 
    assign l_w_b_oe = l_r_state == STATE_MULTIPLY;
    assign l_w_c_we = l_r_state == STATE_MULTIPLY;
    assign l_w_c_oe = l_r_state == STATE_DISPLAY;`
 so i think this file _sequential_multiplier.v_ doesn't need to be modified   
 
 I will work on

2024-11-03 19:12 UTC, DTeodor-Alexaandru approved these changes

2024-11-03 19:21 UTC, merged